### ISSUE TITLE
meta-analysis of medians paper

### ISSUE THREAD

**Issue by softloud** [softloud/varameta#1]
- [x] intro
- [ ] review existing methods
- [ ] outline our method
- [ ] simulation description
- [ ] simulation results
- [ ] simulation analysis
- [ ] look into new methods & incorporate (this will spawn lots of new actions)

**Comment by softloud** [comment]
- [ ] write tests for varameta

**Comment by softloud** [comment]
- [x] do this later

**Comment by softloud** [comment]
- [ ] Find replacement meta-analyses for Pinheiro.
- [ ] Write up with Pinheiro.

**Comment by softloud** [comment]
- [ ] Find a meta-analysis where estimator makes a difference.

**Comment by softloud** [comment]
- [ ] ugh there are new methods, investigate new methods

**Comment by softloud** [comment]
Keeping the TeX and figs separate so that I can troubleshoot both in isolation. Eventually, when manuscript is closer to finalised, then move into .Rmd-generated. Will involve lots of fiddly preamble set up.

# figures

- [x] create .Rmd for it
- [x] put in outline
- [ ] write figs to place, write path

**Comment by softloud** [comment]
# bibliography

- [ ] upgrade texlive
- [ ] compile x 2

**Comment by softloud** [comment]
# density plots

- [ ] need to get `simeta::density_fn` working

**Comment by softloud** [comment]
## pinheiro figures

- [ ] input data 
- [ ] forest plots, before & after

**Comment by softloud** [comment]
## distribution figures

**Comment by softloud** [comment]
- [ ] clear linter tags & tex warnings

**Comment by softloud** [comment]
- [ ] find a better example meta-analysis, one where the change in estiamtor changes the results

**Comment by softloud** [comment]
- [ ] shift paper to overleaf
